FROM localhost/dist2src

RUN dnf -y install epel-release && dnf -y install mock && \
    pip3 install git+git://github.com/packit/ogr.git --upgrade

COPY pkg_survey/survey.py onboard/run-onboard.sh onboard/onboard.py master-branches/* /workdir

CMD bash /workdir/run-onboard.sh
